spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservice-config-acivii-dev
---
spring:
  profiles: test
  application:
    name: microservice-config-acivii-test